# Generated by Django 5.2.4 on 2025-07-19 02:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CashDrawer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("workstation", models.CharField(max_length=50)),
                ("shift_number", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("starting_cash", models.DecimalField(decimal_places=2, max_digits=10)),
                ("hundreds", models.IntegerField(default=0)),
                ("fifties", models.IntegerField(default=0)),
                ("twenties", models.IntegerField(default=0)),
                ("tens", models.IntegerField(default=0)),
                ("fives", models.IntegerField(default=0)),
                ("twos", models.IntegerField(default=0)),
                ("ones", models.IntegerField(default=0)),
                ("half_dollars", models.IntegerField(default=0)),
                ("quarters", models.IntegerField(default=0)),
                ("dimes", models.IntegerField(default=0)),
                ("nickels", models.IntegerField(default=0)),
                ("pennies", models.IntegerField(default=0)),
                ("total_cash", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("workstation", "shift_number", "date")},
            },
        ),
        migrations.CreateModel(
            name="CashDrop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("workstation", models.CharField(max_length=50)),
                ("shift_number", models.CharField(max_length=50)),
                ("date", models.DateField()),
                ("drop_amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("hundreds", models.IntegerField(default=0)),
                ("fifties", models.IntegerField(default=0)),
                ("twenties", models.IntegerField(default=0)),
                ("tens", models.IntegerField(default=0)),
                ("fives", models.IntegerField(default=0)),
                ("twos", models.IntegerField(default=0)),
                ("ones", models.IntegerField(default=0)),
                ("half_dollars", models.IntegerField(default=0)),
                ("quarters", models.IntegerField(default=0)),
                ("dimes", models.IntegerField(default=0)),
                ("nickels", models.IntegerField(default=0)),
                ("pennies", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "drawer_entry",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="cash_drops",
                        to="cash_drop_app1.cashdrawer",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "unique_together": {("workstation", "shift_number", "date")},
            },
        ),
    ]
