FROM python:3.12-slim

WORKDIR /auth

COPY server/auth/requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY server/auth/ .

EXPOSE 8000

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]