# Generated by Django 5.2.4 on 2025-07-16 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("name", models.CharField(max_length=255)),
                ("is_admin", models.BooleanField(default=False)),
                ("totp_secret", models.CharField(blank=True, max_length=32)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.DeleteModel(
            name="UserProfile",
        ),
    ]
