# Generated by Django 5.2.4 on 2025-07-17 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("auth_app", "0002_user_delete_userprofile"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="totp_secret",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
